#ifndef AVS3_GUI_QT_DEFAULT_GLOBAL_H
#define AVS3_GUI_QT_DEFAULT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AVS3_GUI_QT_DEFAULT_LIBRARY)
#  define AVS3_GUI_QT_DEFAULTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AVS3_GUI_QT_DEFAULTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AVS3_GUI_QT_DEFAULT_GLOBAL_H
