#ifndef VALM_GUI_QT_DEFAULT_GLOBAL_H
#define VALM_GUI_QT_DEFAULT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VALM_GUI_QT_DEFAULT_LIBRARY)
#  define VALM_GUI_QT_DEFAULTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VALM_GUI_QT_DEFAULTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VALM_GUI_QT_DEFAULT_GLOBAL_H
